# Setup
title:               journal
tagline:             ''
description:         ''
url:                 https://vasukisunder.github.io
baseurl:             ''
paginate:            100
permalink:           pretty

# About/contact
author:
  name:              vasuki sunder
  url:              
  email:             vasukisunder@gmail.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
