# Setup
title:               Your Blog Title
tagline:             'Your tagline here'
description:         'A brief description of your blog'
url:                 https://vasukisunder.github.io
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Your Name
  url:               https://twitter.com/yourtwitter
  email:             your@email.com

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
